<?php

namespace Test\Example2;

/**
 * PHPUnit test class for Example2
 *
 * Automatically generated by phptcgen version 1.0.0
 */
class Example2Test extends \PHPUnit_Framework_TestCase
{
    /**
     * Test Example2::foo() for when input is x as true
     */
    public function testFooTakesXAsTrue()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example2::foo() for when input is x as false
     */
    public function testFooTakesXAsFalse()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example2::foo() for when input is x as non boolean
     */
    public function testFooTakesXAsNonBoolean()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example2::foo() for when dependency of call to \Example1::multiplyByGlobalPi() results in throwBadGlobalException
     */
    public function testFooWhenMultiplyByGlobalPiThrowBadGlobalException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example2::foo() for when dependency of call to \Example1::multiplyByGlobalPi() results in throwBadInputException
     */
    public function testFooWhenMultiplyByGlobalPiThrowBadInputException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }
}
