<?php

namespace Test\Example3;

/**
 * PHPUnit test class for Example3
 * Automatically generated by phptcgen version 1.0.0
 *
 * @see \Example3\Example3
 */
class Example3Test extends \PHPUnit_Framework_TestCase
{
    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in return true
     */
    public function testBazWhenExample2FooReturnTrue()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in return false
     */
    public function testBazWhenExample2FooReturnFalse()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in throw bad global exception
     */
    public function testBazWhenExample2FooThrowBadGlobalException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in throw bad input exception
     */
    public function testBazWhenExample2FooThrowBadInputException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }
}
