<?php

namespace Test\Example3;

/**
 * PHPUnit test class for Example3
 *
 * Automatically generated by phptcgen version 1.0.0
 */
class Example3Test extends \PHPUnit_Framework_TestCase
{
    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in returnTrue
     */
    public function testBazWhenFooReturnTrue()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in returnFalse
     */
    public function testBazWhenFooReturnFalse()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in throwBadGlobalException
     */
    public function testBazWhenFooThrowBadGlobalException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }

    /**
     * Test Example3::baz() for when dependency of call to \Example2\Example2::foo() results in throwBadInputException
     */
    public function testBazWhenFooThrowBadInputException()
    {
        // ... Put your test code here ...

        // ... Put your assertions here ...
        $this->assertTrue(false);
        $this->markTestIncomplete();
    }
}
